$ANSIBLE_VAULT;1.1;AES256
66316565633137623935316164623136363837396166303438393134613765643066386262636264
6264633765323463393864366434353232626365353336360a316163633235343434353033653164
36326563356637333064333931356263613638343336356537656465663434653831656463646231
6233363932363039640a336430326230373532636532323761393966326563343631626336373565
38643133333766366439356464393865636333323662333633666261313765626331633539623033
38613464663465656563613133626436353166653734353964366665356364666662316262383062
38363436323731343236353437343937623461363463376236336563323434656562373437636236
38616537363134323464363862316335383931376562643761613564363938616162323234623930
61663634626566336363373533306639613034306262623839303638316430653161356432643634
35363162393933353037646135333732626534383265356138646639366230663535343837616132
30393866393162393832343264393437333965623437366234333066663363303364373564383164
31343938393730346436643635643133313132353530316531663238373231623531313733396639
6134
